[[main]]
  name = "Archives"
  identifier = "archives"
  pre = '<i class="fas fa-fw fa-file-archive"></i>'
    url = "archives"
# [[main]]
#   id = "Facebook"
#   parent = "suivez-moi"
#   name = "Github"
#   url = "https://github.com/razonyang/hugo-theme-bootstrap"
#   pre = '<i class="fab fa-fw fa-github"></i>'
# [[main]]
#   id = "GitHub"
#   parent = "suivez-moi"
#   name = "Gitlab"
#   url = "https://github.com/razonyang/hugo-theme-bootstrap"
#   pre = '<i class="fab fa-fw fa-github"></i>'
